version: '3.8'

services:
  # MSSQL Server
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: minimalairbnb-mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Super123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - minimalairbnb-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Super123! -C -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Service
  api:
    build:
      context: .
      dockerfile: src/API/Dockerfile
    container_name: minimalairbnb-api
    ports:
      - "7001:7001"
      - "7002:7002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7001;https://+:7002
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=MinimalAirbnb;User Id=sa;Password=Super123!;TrustServerCertificate=true;MultipleActiveResultSets=true
    depends_on:
      mssql:
        condition: service_healthy
    networks:
      - minimalairbnb-network
    volumes:
      - ./src/API:/app/src/API
      - /app/src/API/bin
      - /app/src/API/obj

volumes:
  mssql_data:
    driver: local

networks:
  minimalairbnb-network:
    driver: bridge 