using FluentMigrator;

namespace MinimalAirbnb.Infrastructure.Migrations;

/// <summary>
/// Tüm tabloları oluşturan migration
/// </summary>
[Migration(20240101000001)]
public class CreateAllTables : Migration
{
    public override void Up()
    {
        // Identity tabloları
        Create.Table("AspNetRoles")
            .WithColumn("Id").AsGuid().PrimaryKey().NotNullable()
            .WithColumn("Name").AsString(256).Nullable()
            .WithColumn("NormalizedName").AsString(256).Nullable()
            .WithColumn("ConcurrencyStamp").AsString().Nullable();

        Create.Table("AspNetUsers")
            .WithColumn("Id").AsGuid().PrimaryKey().NotNullable()
            .WithColumn("UserName").AsString(256).Nullable()
            .WithColumn("NormalizedUserName").AsString(256).Nullable()
            .WithColumn("Email").AsString(256).Nullable()
            .WithColumn("NormalizedEmail").AsString(256).Nullable()
            .WithColumn("EmailConfirmed").AsBoolean().NotNullable()
            .WithColumn("PasswordHash").AsString().Nullable()
            .WithColumn("SecurityStamp").AsString().Nullable()
            .WithColumn("ConcurrencyStamp").AsString().Nullable()
            .WithColumn("PhoneNumber").AsString().Nullable()
            .WithColumn("PhoneNumberConfirmed").AsBoolean().NotNullable()
            .WithColumn("TwoFactorEnabled").AsBoolean().NotNullable()
            .WithColumn("LockoutEnd").AsDateTimeOffset().Nullable()
            .WithColumn("LockoutEnabled").AsBoolean().NotNullable()
            .WithColumn("AccessFailedCount").AsInt32().NotNullable()
            .WithColumn("FirstName").AsString(50).NotNullable()
            .WithColumn("LastName").AsString(50).NotNullable()
            .WithColumn("ProfilePicture").AsString(500).Nullable()
            .WithColumn("ProfilePictureUrl").AsString(500).Nullable()
            .WithColumn("Bio").AsString(1000).Nullable()
            .WithColumn("DateOfBirth").AsDate().Nullable()
            .WithColumn("Address").AsString(500).Nullable()
            .WithColumn("City").AsString(100).Nullable()
            .WithColumn("Country").AsString(100).Nullable()
            .WithColumn("PostalCode").AsString(20).Nullable()
            .WithColumn("UserType").AsInt32().NotNullable()
            .WithColumn("IsVerified").AsBoolean().NotNullable()
            .WithColumn("IsActive").AsBoolean().NotNullable()
            .WithColumn("LastLoginDate").AsDateTime().Nullable()
            .WithColumn("LoginCount").AsInt32().NotNullable();

        Create.Table("AspNetRoleClaims")
            .WithColumn("Id").AsInt32().PrimaryKey().Identity().NotNullable()
            .WithColumn("RoleId").AsGuid().NotNullable()
            .WithColumn("ClaimType").AsString().Nullable()
            .WithColumn("ClaimValue").AsString().Nullable();

        Create.Table("AspNetUserClaims")
            .WithColumn("Id").AsInt32().PrimaryKey().Identity().NotNullable()
            .WithColumn("UserId").AsGuid().NotNullable()
            .WithColumn("ClaimType").AsString().Nullable()
            .WithColumn("ClaimValue").AsString().Nullable();

        Create.Table("AspNetUserLogins")
            .WithColumn("LoginProvider").AsString(450).PrimaryKey().NotNullable()
            .WithColumn("ProviderKey").AsString(450).PrimaryKey().NotNullable()
            .WithColumn("ProviderDisplayName").AsString().Nullable()
            .WithColumn("UserId").AsGuid().NotNullable();

        Create.Table("AspNetUserRoles")
            .WithColumn("UserId").AsGuid().PrimaryKey().NotNullable()
            .WithColumn("RoleId").AsGuid().PrimaryKey().NotNullable();

        Create.Table("AspNetUserTokens")
            .WithColumn("UserId").AsGuid().PrimaryKey().NotNullable()
            .WithColumn("LoginProvider").AsString(450).PrimaryKey().NotNullable()
            .WithColumn("Name").AsString(450).PrimaryKey().NotNullable()
            .WithColumn("Value").AsString().Nullable();

        // İş domain tabloları
        Create.Table("Properties")
            .WithColumn("Id").AsGuid().PrimaryKey().NotNullable()
            .WithColumn("HostId").AsGuid().NotNullable()
            .WithColumn("CreatorUserId").AsGuid().Nullable()
            .WithColumn("CreatorIP").AsString(50).Nullable()
            .WithColumn("CreatedDate").AsDateTime().NotNullable()
            .WithColumn("ModifierUserId").AsGuid().Nullable()
            .WithColumn("ModifierIP").AsString(50).Nullable()
            .WithColumn("ModifiedDate").AsDateTime().Nullable()
            .WithColumn("IsDeleted").AsBoolean().NotNullable()
            .WithColumn("IsPublish").AsBoolean().NotNullable()
            .WithColumn("DisplayOrder").AsInt32().NotNullable()
            .WithColumn("Title").AsString(200).NotNullable()
            .WithColumn("Description").AsString(2000).NotNullable()
            .WithColumn("PropertyType").AsInt32().NotNullable()
            .WithColumn("BedroomCount").AsInt32().NotNullable()
            .WithColumn("BedCount").AsInt32().NotNullable()
            .WithColumn("BathroomCount").AsInt32().NotNullable()
            .WithColumn("MaxGuestCount").AsInt32().NotNullable()
            .WithColumn("PricePerNight").AsDecimal(18, 2).NotNullable()
            .WithColumn("CleaningFee").AsDecimal(18, 2).NotNullable()
            .WithColumn("ServiceFee").AsDecimal(18, 2).NotNullable()
            .WithColumn("Address").AsString(500).NotNullable()
            .WithColumn("City").AsString(100).NotNullable()
            .WithColumn("Country").AsString(100).NotNullable()
            .WithColumn("PostalCode").AsString(20).Nullable()
            .WithColumn("Latitude").AsDouble().NotNullable()
            .WithColumn("Longitude").AsDouble().NotNullable()
            .WithColumn("HasWifi").AsBoolean().NotNullable()
            .WithColumn("HasAirConditioning").AsBoolean().NotNullable()
            .WithColumn("HasKitchen").AsBoolean().NotNullable()
            .WithColumn("HasParking").AsBoolean().NotNullable()
            .WithColumn("HasPool").AsBoolean().NotNullable()
            .WithColumn("AllowsPets").AsBoolean().NotNullable()
            .WithColumn("AllowsSmoking").AsBoolean().NotNullable()
            .WithColumn("MinimumStayDays").AsInt32().NotNullable()
            .WithColumn("MinimumStay").AsInt32().NotNullable()
            .WithColumn("MaximumStayDays").AsInt32().NotNullable()
            .WithColumn("MaximumStay").AsInt32().NotNullable()
            .WithColumn("CancellationPolicyDays").AsInt32().NotNullable()
            .WithColumn("CancellationPolicy").AsString(500).Nullable()
            .WithColumn("HouseRules").AsString(1000).Nullable()
            .WithColumn("Amenities").AsString(1000).Nullable()
            .WithColumn("IsActive").AsBoolean().NotNullable()
            .WithColumn("IsInstantBookable").AsBoolean().NotNullable()
            .WithColumn("AverageRating").AsDecimal(3, 2).NotNullable()
            .WithColumn("TotalReviews").AsInt32().NotNullable()
            .WithColumn("ViewCount").AsInt32().NotNullable()
            .WithColumn("FavoriteCount").AsInt32().NotNullable()
            .WithColumn("ReservationCount").AsInt32().NotNullable()
            .WithColumn("UpdatedDate").AsDateTime().Nullable();

        Create.Table("Reservations")
            .WithColumn("Id").AsGuid().PrimaryKey().NotNullable()
            .WithColumn("GuestId").AsGuid().NotNullable()
            .WithColumn("CreatorUserId").AsGuid().Nullable()
            .WithColumn("CreatorIP").AsString(50).Nullable()
            .WithColumn("CreatedDate").AsDateTime().NotNullable()
            .WithColumn("ModifierUserId").AsGuid().Nullable()
            .WithColumn("ModifierIP").AsString(50).Nullable()
            .WithColumn("ModifiedDate").AsDateTime().Nullable()
            .WithColumn("IsDeleted").AsBoolean().NotNullable()
            .WithColumn("IsPublish").AsBoolean().NotNullable()
            .WithColumn("DisplayOrder").AsInt32().NotNullable()
            .WithColumn("PropertyId").AsGuid().NotNullable()
            .WithColumn("CheckInDate").AsDateTime().NotNullable()
            .WithColumn("CheckOutDate").AsDateTime().NotNullable()
            .WithColumn("GuestCount").AsInt32().NotNullable()
            .WithColumn("TotalDays").AsInt32().NotNullable()
            .WithColumn("PricePerNight").AsDecimal(18, 2).NotNullable()
            .WithColumn("CleaningFee").AsDecimal(18, 2).NotNullable()
            .WithColumn("ServiceFee").AsDecimal(18, 2).NotNullable()
            .WithColumn("TotalPrice").AsDecimal(18, 2).NotNullable()
            .WithColumn("Status").AsInt32().NotNullable()
            .WithColumn("SpecialRequests").AsString(1000).Nullable()
            .WithColumn("CancellationReason").AsString(500).Nullable()
            .WithColumn("CancellationDate").AsDateTime().Nullable()
            .WithColumn("CancelledByUserId").AsGuid().Nullable()
            .WithColumn("ConfirmationDate").AsDateTime().Nullable()
            .WithColumn("ConfirmedByUserId").AsGuid().Nullable()
            .WithColumn("CheckInTime").AsTime().NotNullable()
            .WithColumn("CheckOutTime").AsTime().NotNullable()
            .WithColumn("ActualCheckInDate").AsDateTime().Nullable()
            .WithColumn("ActualCheckOutDate").AsDateTime().Nullable()
            .WithColumn("UpdatedDate").AsDateTime().Nullable();

        Create.Table("Reviews")
            .WithColumn("Id").AsGuid().PrimaryKey().NotNullable()
            .WithColumn("GuestId").AsGuid().NotNullable()
            .WithColumn("CreatorUserId").AsGuid().Nullable()
            .WithColumn("CreatorIP").AsString(50).Nullable()
            .WithColumn("CreatedDate").AsDateTime().NotNullable()
            .WithColumn("ModifierUserId").AsGuid().Nullable()
            .WithColumn("ModifierIP").AsString(50).Nullable()
            .WithColumn("ModifiedDate").AsDateTime().Nullable()
            .WithColumn("IsDeleted").AsBoolean().NotNullable()
            .WithColumn("IsPublish").AsBoolean().NotNullable()
            .WithColumn("DisplayOrder").AsInt32().NotNullable()
            .WithColumn("PropertyId").AsGuid().NotNullable()
            .WithColumn("ReservationId").AsGuid().Nullable()
            .WithColumn("Rating").AsInt32().NotNullable()
            .WithColumn("Comment").AsString(2000).NotNullable()
            .WithColumn("HostResponse").AsString(2000).Nullable()
            .WithColumn("HostResponseDate").AsDateTime().Nullable()
            .WithColumn("HostResponseUserId").AsGuid().Nullable()
            .WithColumn("IsApproved").AsBoolean().NotNullable()
            .WithColumn("IsRejected").AsBoolean().NotNullable()
            .WithColumn("RejectionReason").AsString(500).Nullable()
            .WithColumn("ModeratedByUserId").AsGuid().Nullable()
            .WithColumn("ModerationDate").AsDateTime().Nullable()
            .WithColumn("LikeCount").AsInt32().NotNullable()
            .WithColumn("DislikeCount").AsInt32().NotNullable();

        Create.Table("Payments")
            .WithColumn("Id").AsGuid().PrimaryKey().NotNullable()
            .WithColumn("UserId").AsGuid().NotNullable()
            .WithColumn("CreatorUserId").AsGuid().Nullable()
            .WithColumn("CreatorIP").AsString(50).Nullable()
            .WithColumn("CreatedDate").AsDateTime().NotNullable()
            .WithColumn("ModifierUserId").AsGuid().Nullable()
            .WithColumn("ModifierIP").AsString(50).Nullable()
            .WithColumn("ModifiedDate").AsDateTime().Nullable()
            .WithColumn("IsDeleted").AsBoolean().NotNullable()
            .WithColumn("IsPublish").AsBoolean().NotNullable()
            .WithColumn("DisplayOrder").AsInt32().NotNullable()
            .WithColumn("ReservationId").AsGuid().NotNullable()
            .WithColumn("Amount").AsDecimal(18, 2).NotNullable()
            .WithColumn("PaymentMethod").AsInt32().NotNullable()
            .WithColumn("Status").AsInt32().NotNullable()
            .WithColumn("TransactionId").AsString(100).Nullable()
            .WithColumn("ProviderReferenceId").AsString(100).Nullable()
            .WithColumn("PaymentDate").AsDateTime().Nullable()
            .WithColumn("RefundAmount").AsDecimal(18, 2).Nullable()
            .WithColumn("RefundDate").AsDateTime().Nullable()
            .WithColumn("RefundReason").AsString(500).Nullable()
            .WithColumn("ErrorMessage").AsString(1000).Nullable()
            .WithColumn("RetryCount").AsInt32().NotNullable()
            .WithColumn("LastRetryDate").AsDateTime().Nullable()
            .WithColumn("PaymentProvider").AsString(100).Nullable()
            .WithColumn("LastFourDigits").AsString(4).Nullable()
            .WithColumn("CardType").AsString(50).Nullable()
            .WithColumn("Currency").AsString(3).NotNullable()
            .WithColumn("ExchangeRate").AsDecimal(18, 6).Nullable()
            .WithColumn("OriginalAmount").AsDecimal(18, 2).Nullable()
            .WithColumn("OriginalCurrency").AsString(3).Nullable();

        Create.Table("Messages")
            .WithColumn("Id").AsGuid().PrimaryKey().NotNullable()
            .WithColumn("SenderId").AsGuid().NotNullable()
            .WithColumn("CreatorUserId").AsGuid().Nullable()
            .WithColumn("CreatorIP").AsString(50).Nullable()
            .WithColumn("CreatedDate").AsDateTime().NotNullable()
            .WithColumn("ModifierUserId").AsGuid().Nullable()
            .WithColumn("ModifierIP").AsString(50).Nullable()
            .WithColumn("ModifiedDate").AsDateTime().Nullable()
            .WithColumn("IsDeleted").AsBoolean().NotNullable()
            .WithColumn("IsPublish").AsBoolean().NotNullable()
            .WithColumn("DisplayOrder").AsInt32().NotNullable()
            .WithColumn("ReceiverId").AsGuid().NotNullable()
            .WithColumn("ReservationId").AsGuid().Nullable()
            .WithColumn("PropertyId").AsGuid().Nullable()
            .WithColumn("Subject").AsString(200).NotNullable()
            .WithColumn("Content").AsString(2000).NotNullable()
            .WithColumn("IsRead").AsBoolean().NotNullable()
            .WithColumn("ReadDate").AsDateTime().Nullable()
            .WithColumn("ReplyToMessageId").AsGuid().Nullable()
            .WithColumn("MessageType").AsInt32().NotNullable()
            .WithColumn("Priority").AsInt32().NotNullable()
            .WithColumn("Category").AsInt32().NotNullable()
            .WithColumn("AttachmentUrl").AsString(500).Nullable()
            .WithColumn("AttachmentName").AsString(200).Nullable()
            .WithColumn("AttachmentSize").AsInt64().Nullable()
            .WithColumn("AttachmentType").AsString(100).Nullable()
            .WithColumn("IsEncrypted").AsBoolean().NotNullable()
            .WithColumn("IsArchived").AsBoolean().NotNullable()
            .WithColumn("ArchivedDate").AsDateTime().Nullable()
            .WithColumn("ArchivedByUserId").AsGuid().Nullable()
            .WithColumn("UpdatedDate").AsDateTime().Nullable();

        Create.Table("Favorites")
            .WithColumn("Id").AsGuid().PrimaryKey().NotNullable()
            .WithColumn("UserId").AsGuid().NotNullable()
            .WithColumn("CreatorUserId").AsGuid().Nullable()
            .WithColumn("CreatorIP").AsString(50).Nullable()
            .WithColumn("CreatedDate").AsDateTime().NotNullable()
            .WithColumn("ModifierUserId").AsGuid().Nullable()
            .WithColumn("ModifierIP").AsString(50).Nullable()
            .WithColumn("ModifiedDate").AsDateTime().Nullable()
            .WithColumn("IsDeleted").AsBoolean().NotNullable()
            .WithColumn("IsPublish").AsBoolean().NotNullable()
            .WithColumn("DisplayOrder").AsInt32().NotNullable()
            .WithColumn("PropertyId").AsGuid().NotNullable()
            .WithColumn("Note").AsString(500).Nullable()
            .WithColumn("Category").AsString(100).Nullable()
            .WithColumn("Tags").AsString(500).Nullable()
            .WithColumn("SortOrder").AsInt32().Nullable()
            .WithColumn("IsPrivate").AsBoolean().NotNullable()
            .WithColumn("IsShared").AsBoolean().NotNullable()
            .WithColumn("SharedDate").AsDateTime().Nullable()
            .WithColumn("ShareLink").AsString(500).Nullable()
            .WithColumn("VisitCount").AsInt32().NotNullable()
            .WithColumn("LastVisitDate").AsDateTime().Nullable()
            .WithColumn("ReminderDate").AsDateTime().Nullable()
            .WithColumn("ReminderNote").AsString(200).Nullable()
            .WithColumn("ReminderSent").AsBoolean().NotNullable();

        Create.Table("PropertyPhotos")
            .WithColumn("Id").AsGuid().PrimaryKey().NotNullable()
            .WithColumn("PropertyId").AsGuid().NotNullable()
            .WithColumn("CreatorUserId").AsGuid().Nullable()
            .WithColumn("CreatorIP").AsString(50).Nullable()
            .WithColumn("CreatedDate").AsDateTime().NotNullable()
            .WithColumn("ModifierUserId").AsGuid().Nullable()
            .WithColumn("ModifierIP").AsString(50).Nullable()
            .WithColumn("ModifiedDate").AsDateTime().Nullable()
            .WithColumn("IsDeleted").AsBoolean().NotNullable()
            .WithColumn("IsPublish").AsBoolean().NotNullable()
            .WithColumn("DisplayOrder").AsInt32().NotNullable()
            .WithColumn("PhotoUrl").AsString(500).NotNullable()
            .WithColumn("Caption").AsString(200).Nullable()
            .WithColumn("Description").AsString(1000).Nullable()
            .WithColumn("IsMainPhoto").AsBoolean().NotNullable()
            .WithColumn("SortOrder").AsInt32().NotNullable()
            .WithColumn("FileName").AsString(200).Nullable()
            .WithColumn("FileType").AsString(50).Nullable()
            .WithColumn("FileSize").AsInt64().Nullable()
            .WithColumn("Width").AsInt32().Nullable()
            .WithColumn("Height").AsInt32().Nullable()
            .WithColumn("Resolution").AsInt32().Nullable()
            .WithColumn("Quality").AsInt32().Nullable()
            .WithColumn("Tags").AsString(500).Nullable()
            .WithColumn("Category").AsString(100).Nullable()
            .WithColumn("IsApproved").AsBoolean().NotNullable()
            .WithColumn("IsRejected").AsBoolean().NotNullable()
            .WithColumn("RejectionReason").AsString(500).Nullable()
            .WithColumn("ModeratedByUserId").AsGuid().Nullable()
            .WithColumn("ModerationDate").AsDateTime().Nullable()
            .WithColumn("ViewCount").AsInt32().NotNullable()
            .WithColumn("LikeCount").AsInt32().NotNullable()
            .WithColumn("CommentCount").AsInt32().NotNullable()
            .WithColumn("ShareCount").AsInt32().NotNullable()
            .WithColumn("DownloadCount").AsInt32().NotNullable();
    }

    public override void Down()
    {
        // Tabloları sil
        Delete.Table("PropertyPhotos");
        Delete.Table("Favorites");
        Delete.Table("Messages");
        Delete.Table("Payments");
        Delete.Table("Reviews");
        Delete.Table("Reservations");
        Delete.Table("Properties");
        Delete.Table("AspNetUserTokens");
        Delete.Table("AspNetUserRoles");
        Delete.Table("AspNetUserLogins");
        Delete.Table("AspNetUserClaims");
        Delete.Table("AspNetRoleClaims");
        Delete.Table("AspNetUsers");
        Delete.Table("AspNetRoles");
    }
} 